/**
 * GSD (Get Shit Done) Executor
 * Implements GSD spec-driven development workflow for OMK
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync, readdirSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

export interface GSDProject {
  name: string;
  description: string;
  techStack: string[];
  requirements: {
    v1: string[];
    v2: string[];
    outOfScope: string[];
  };
  phases: GSDPhase[];
  currentPhase: number;
  state: {
    decisions: string[];
    blockers: string[];
    completedTasks: string[];
  };
}

export interface GSDPhase {
  number: number;
  title: string;
  description: string;
  status: 'pending' | 'discussing' | 'planning' | 'executing' | 'verifying' | 'completed';
  plans: GSDPlan[];
  context?: string;
  research?: string;
  verification?: string;
}

export interface GSDPlan {
  id: string;
  name: string;
  tasks: GSDTask[];
  status: 'pending' | 'running' | 'completed' | 'failed';
  summary?: string;
}

export interface GSDTask {
  id: string;
  name: string;
  description: string;
  files: string[];
  action: string;
  verification: string;
  status: 'pending' | 'completed' | 'failed';
}

export class GSDExecutor {
  private cwd: string;
  private planningDir: string;
  private project: GSDProject | null = null;

  constructor(cwd: string) {
    this.cwd = cwd;
    this.planningDir = join(cwd, '.planning');
  }

  /**
   * Initialize new GSD project
   */
  async newProject(name?: string): Promise<void> {
    this.ensurePlanningDir();
    
    console.log('\n\x1b[36m[GSD] Initializing new project...\x1b[0m\n');
    
    // Create PROJECT.md
    const projectContent = `# ${name || 'New Project'}

## Vision
Project description will be captured during discussion phase.

## Goals
- Define clear project objectives
- Identify target users
- Establish success metrics

## Tech Stack
To be determined during planning.

## Constraints
- Budget limitations
- Timeline requirements
- Technical constraints

---
Generated by GSD (Get Shit Done)
`;
    writeFileSync(join(this.planningDir, 'PROJECT.md'), projectContent);
    
    // Create empty REQUIREMENTS.md
    const requirementsContent = `# Requirements

## v1 (MVP)
- [ ] Requirements to be gathered during discuss phase

## v2 (Future)
- [ ] Features planned for next iteration

## Out of Scope
- Features explicitly not included

---
Generated by GSD
`;
    writeFileSync(join(this.planningDir, 'REQUIREMENTS.md'), requirementsContent);
    
    // Create empty ROADMAP.md
    const roadmapContent = `# Roadmap

## Phase 1: Foundation
- Status: pending
- Description: Project setup and core infrastructure

## Phase 2: Core Features  
- Status: pending
- Description: Main functionality implementation

## Phase 3: Polish & Launch
- Status: pending
- Description: Testing, optimization, and deployment

---
Generated by GSD
`;
    writeFileSync(join(this.planningDir, 'ROADMAP.md'), roadmapContent);
    
    // Create STATE.md
    const stateContent = `# State

## Current Position
- Phase: Not started
- Status: Initializing

## Decisions
- [ ] Project scope to be defined

## Blockers
- None

## Completed Tasks
- Project initialized

---
Generated by GSD
`;
    writeFileSync(join(this.planningDir, 'STATE.md'), stateContent);
    
    // Create todos directory
    mkdirSync(join(this.planningDir, 'todos'), { recursive: true });
    
    console.log('\x1b[32m[OK] GSD project initialized!\x1b[0m\n');
    console.log('Next steps:');
    console.log('  1. $gsd-discuss-phase 1 - Define phase 1 requirements');
    console.log('  2. $gsd-plan-phase 1 - Research and plan');
    console.log('  3. $gsd-execute-phase 1 - Execute plans\n');
  }

  /**
   * Map existing codebase
   */
  async mapCodebase(): Promise<void> {
    console.log('\n\x1b[36m[GSD] Mapping codebase...\x1b[0m\n');
    
    this.ensurePlanningDir();
    
    // Detect tech stack
    const techStack = this.detectTechStack();
    
    // Analyze directory structure
    const structure = this.analyzeStructure();
    
    // Create codebase map
    const mapContent = `# Codebase Map

Generated: ${new Date().toISOString()}

## Tech Stack
${techStack.map(t => `- ${t}`).join('\n')}

## Directory Structure
\`\`\`
${structure}
\`\`\`

## Key Files
- Entry points: (to be identified)
- Configuration: (to be identified)
- Core modules: (to be identified)

## Architecture Notes
- Patterns detected: (analysis needed)
- Conventions: (to be documented)
- Dependencies: (to be mapped)

---
Generated by GSD
`;
    
    mkdirSync(join(this.planningDir, 'research'), { recursive: true });
    writeFileSync(join(this.planningDir, 'research', 'CODEBASE-MAP.md'), mapContent);
    
    console.log('\x1b[32m[OK] Codebase mapped!\x1b[0m\n');
    console.log(`Detected: ${techStack.join(', ')}\n`);
    console.log('Next: Run $gsd-new-project to create GSD structure\n');
  }

  /**
   * Discuss phase - gather requirements
   */
  async discussPhase(phaseNumber: number): Promise<void> {
    console.log(`\n\x1b[36m[GSD] Discussing Phase ${phaseNumber}...\x1b[0m\n`);
    
    if (!this.isInitialized()) {
      console.log('\x1b[33m[Warning] GSD not initialized. Run $gsd-new-project first.\x1b[0m\n');
      return;
    }
    
    // Create context file for this phase
    const contextContent = `# Phase ${phaseNumber} Context

Generated: ${new Date().toISOString()}

## Phase Goals
- To be defined through discussion

## Open Questions
- What needs to be built in this phase?
- What are the acceptance criteria?
- What are the technical considerations?

## Decisions Made
- [ ] Pending discussion

## Assumptions
- [ ] To be validated

## Risks
- [ ] To be identified

---
Next: Run $gsd-plan-phase ${phaseNumber}
`;
    
    writeFileSync(
      join(this.planningDir, `${String(phaseNumber).padStart(2, '0')}-CONTEXT.md`),
      contextContent
    );
    
    // Update STATE.md
    this.updateState({
      currentPhase: phaseNumber,
      status: 'discussing'
    });
    
    console.log('\x1b[32m[OK] Phase context template created!\x1b[0m\n');
    console.log(`File: ${String(phaseNumber).padStart(2, '0')}-CONTEXT.md\n`);
    console.log('Fill in the context file with phase requirements,');
    console.log(`then run: $gsd-plan-phase ${phaseNumber}\n`);
  }

  /**
   * Plan phase - research and create plans
   */
  async planPhase(phaseNumber: number): Promise<void> {
    console.log(`\n\x1b[36m[GSD] Planning Phase ${phaseNumber}...\x1b[0m\n`);
    
    if (!this.isInitialized()) {
      console.log('\x1b[33m[Warning] GSD not initialized.\x1b[0m\n');
      return;
    }
    
    // Create research document
    const researchContent = `# Phase ${phaseNumber} Research

Generated: ${new Date().toISOString()}

## Research Questions
- What technologies/patterns should we use?
- What are the best practices?
- What are potential pitfalls?

## Findings
- [ ] To be researched

## Architecture Decisions
- [ ] ADR: (Architecture Decision Records)

## References
- Documentation links
- Code examples
- Similar implementations

---
Research for Phase ${phaseNumber}
`;
    
    writeFileSync(
      join(this.planningDir, `${String(phaseNumber).padStart(2, '0')}-RESEARCH.md`),
      researchContent
    );
    
    // Create plan template
    const planContent = `# Phase ${phaseNumber} Plan 01

Generated: ${new Date().toISOString()}

## Overview
Plan for implementing Phase ${phaseNumber} requirements.

## Tasks

### Task 1: [Task Name]
- **Files:** 
  - \`src/example.ts\`
- **Action:**
  - Implement feature X
  - Handle edge case Y
- **Verify:**
  - Test passes
  - Feature works as expected

### Task 2: [Task Name]
- **Files:**
  - \`src/example.test.ts\`
- **Action:**
  - Write tests
- **Verify:**
  - Coverage > 80%

## Dependencies
- Task 2 depends on Task 1

## Estimated Effort
- Small (< 1 day)
- Medium (1-3 days)
- Large (3-5 days)

---
Plan for Phase ${phaseNumber}
`;
    
    writeFileSync(
      join(this.planningDir, `${String(phaseNumber).padStart(2, '0')}-01-PLAN.md`),
      planContent
    );
    
    // Update STATE.md
    this.updateState({
      currentPhase: phaseNumber,
      status: 'planning'
    });
    
    console.log('\x1b[32m[OK] Planning templates created!\x1b[0m\n');
    console.log('Files created:');
    console.log(`  - ${String(phaseNumber).padStart(2, '0')}-RESEARCH.md`);
    console.log(`  - ${String(phaseNumber).padStart(2, '0')}-01-PLAN.md\n`);
    console.log(`Edit these files, then run: $gsd-execute-phase ${phaseNumber}\n`);
  }

  /**
   * Execute phase - run plans
   */
  async executePhase(phaseNumber: number): Promise<void> {
    console.log(`\n\x1b[36m[GSD] Executing Phase ${phaseNumber}...\x1b[0m\n`);
    
    if (!this.isInitialized()) {
      console.log('\x1b[33m[Warning] GSD not initialized.\x1b[0m\n');
      return;
    }
    
    // Find plan files for this phase
    const planFiles = this.getPlanFiles(phaseNumber);
    
    if (planFiles.length === 0) {
      console.log(`\x1b[33m[Warning] No plans found for Phase ${phaseNumber}\x1b[0m\n`);
      console.log(`Run $gsd-plan-phase ${phaseNumber} first.\n`);
      return;
    }
    
    console.log(`Found ${planFiles.length} plan(s) to execute:\n`);
    planFiles.forEach((f, i) => {
      console.log(`  ${i + 1}. ${f}`);
    });
    
    console.log('\n\x1b[36m[Execution Mode]\x1b[0m');
    console.log('This is where AI would execute the plans.');
    console.log('In OMK, this triggers the actual implementation.\n');
    
    // Create summary template
    const summaryContent = `# Phase ${phaseNumber} Plan 01 Summary

Generated: ${new Date().toISOString()}

## Completed Tasks
- [ ] Task 1
- [ ] Task 2

## Changes Made
- Files modified:
  - \`src/example.ts\`
- Lines added: XX
- Lines removed: XX

## Git Commits
- \`abc123\` feat: implement feature X
- \`def456\` test: add tests for feature X

## Verification Results
- All tests passing
- Feature working as expected

## Notes
- Challenges encountered
- Decisions made during execution

---
Summary for Phase ${phaseNumber}
`;
    
    writeFileSync(
      join(this.planningDir, `${String(phaseNumber).padStart(2, '0')}-01-SUMMARY.md`),
      summaryContent
    );
    
    // Update STATE.md
    this.updateState({
      currentPhase: phaseNumber,
      status: 'executing'
    });
    
    console.log('\x1b[32m[OK] Execution template created!\x1b[0m\n');
    console.log('AI will now execute the plans.');
    console.log('After execution, run verification:\n');
    console.log(`$gsd-verify-work ${phaseNumber}\n`);
  }

  /**
   * Verify work - UAT
   */
  async verifyWork(phaseNumber: number): Promise<void> {
    console.log(`\n\x1b[36m[GSD] Verifying Phase ${phaseNumber}...\x1b[0m\n`);
    
    // Create verification document
    const verificationContent = `# Phase ${phaseNumber} Verification

Generated: ${new Date().toISOString()}

## Test Results

### Functional Tests
- [ ] Feature X works correctly
- [ ] Edge cases handled
- [ ] Error messages clear

### Integration Tests
- [ ] Works with existing features
- [ ] Database migrations applied
- [ ] API contracts maintained

### Quality Checks
- [ ] Code review passed
- [ ] Tests coverage acceptable
- [ ] No linting errors
- [ ] Type checking passes

## User Acceptance Testing

### Scenario 1: [Use Case]
**Steps:**
1. Action 1
2. Action 2

**Expected:** Result
**Actual:** (to be filled during testing)
**Status:** \[ ] Pass / \[ ] Fail

## Issues Found
- [ ] Issue 1
- [ ] Issue 2

## Fix Plans (if issues found)
If verification fails, create fix plans:
- Plan: Fix issue X
- Plan: Fix issue Y

## Sign-off
- [ ] All tests passing
- [ ] UAT completed
- [ ] Ready to ship

---
Verification for Phase ${phaseNumber}
`;
    
    writeFileSync(
      join(this.planningDir, `${String(phaseNumber).padStart(2, '0')}-VERIFICATION.md`),
      verificationContent
    );
    
    // Update STATE.md
    this.updateState({
      currentPhase: phaseNumber,
      status: 'verifying'
    });
    
    console.log('\x1b[32m[OK] Verification template created!\x1b[0m\n');
    console.log('Perform manual testing and fill in results.');
    console.log('If all tests pass, create PR:\n');
    console.log(`$gsd-ship ${phaseNumber}\n`);
  }

  /**
   * Ship phase - create PR
   */
  async ship(phaseNumber: number): Promise<void> {
    console.log(`\n\x1b[36m[GSD] Shipping Phase ${phaseNumber}...\x1b[0m\n`);
    
    // Generate PR description
    const prContent = `# Phase ${phaseNumber} Implementation

## Summary
Implementation of Phase ${phaseNumber} as per GSD planning.

## Changes
- Implemented features per plan
- Added tests
- Updated documentation

## Planning Documents
- Context: ${String(phaseNumber).padStart(2, '0')}-CONTEXT.md
- Research: ${String(phaseNumber).padStart(2, '0')}-RESEARCH.md
- Plan: ${String(phaseNumber).padStart(2, '0')}-01-PLAN.md
- Summary: ${String(phaseNumber).padStart(2, '0')}-01-SUMMARY.md

## Verification
- [ ] All tests passing
- [ ] UAT completed
- [ ] Code reviewed

## Related
- Closes #(issue numbers)

---
Generated by GSD
`;
    
    writeFileSync(
      join(this.planningDir, `${String(phaseNumber).padStart(2, '0')}-PR.md`),
      prContent
    );
    
    // Update STATE.md
    this.updateState({
      currentPhase: phaseNumber,
      status: 'completed'
    });
    
    console.log('\x1b[32m[OK] PR template created!\x1b[0m\n');
    console.log('Create PR with:');
    console.log('  git checkout -b gsd/phase-' + phaseNumber);
    console.log('  git add .');
    console.log('  git commit -m "feat: implement phase ' + phaseNumber + '"');
    console.log('  git push origin gsd/phase-' + phaseNumber);
    console.log('\nThen open PR on GitHub.\n');
  }

  /**
   * Quick task execution
   */
  async quick(task: string): Promise<void> {
    console.log('\n\x1b[36m[GSD] Quick Task: ' + task + '\x1b[0m\n');
    
    this.ensurePlanningDir();
    mkdirSync(join(this.planningDir, 'quick'), { recursive: true });
    
    const timestamp = Date.now();
    const planContent = `# Quick Task: ${task}

Generated: ${new Date().toISOString()}

## Task
${task}

## Plan
- [ ] Analyze requirements
- [ ] Implement solution
- [ ] Test changes
- [ ] Commit work

## Notes
Quick task execution with GSD tracking.

---
Quick Task #${timestamp}
`;
    
    writeFileSync(
      join(this.planningDir, 'quick', `${timestamp}-PLAN.md`),
      planContent
    );
    
    console.log('\x1b[32m[OK] Quick task plan created!\x1b[0m\n');
    console.log(`Execute the task and update the plan file.\n`);
  }

  /**
   * Show GSD progress
   */
  async progress(): Promise<void> {
    console.log('\n\x1b[1m📊 GSD Progress\x1b[0m\n');
    
    if (!this.isInitialized()) {
      console.log('GSD not initialized.\n');
      console.log('Run: $gsd-new-project\n');
      return;
    }
    
    // List all planning files
    const files = readdirSync(this.planningDir);
    const planningFiles = files.filter(f => f.endsWith('.md'));
    
    console.log(`Planning files (${planningFiles.length}):`);
    planningFiles.forEach(f => {
      console.log(`  - ${f}`);
    });
    
    // Show current state
    try {
      const stateContent = readFileSync(join(this.planningDir, 'STATE.md'), 'utf-8');
      const currentMatch = stateContent.match(/Phase: (.+)/);
      const statusMatch = stateContent.match(/Status: (.+)/);
      
      if (currentMatch || statusMatch) {
        console.log('\n\x1b[36mCurrent State:\x1b[0m');
        if (currentMatch) console.log(`  Phase: ${currentMatch[1]}`);
        if (statusMatch) console.log(`  Status: ${statusMatch[1]}`);
      }
    } catch {
      // Ignore
    }
    
    console.log('\nNext steps:');
    console.log('  $gsd-next - Auto-detect and run next step\n');
  }

  /**
   * Auto-detect next step
   */
  async next(): Promise<void> {
    console.log('\n\x1b[36m[GSD] Detecting next step...\x1b[0m\n');
    
    if (!this.isInitialized()) {
      console.log('Run: $gsd-new-project\n');
      return;
    }
    
    // Simple logic to detect next step
    const files = readdirSync(this.planningDir);
    
    // Check for phases
    for (let i = 1; i <= 10; i++) {
      const phasePrefix = String(i).padStart(2, '0');
      const hasContext = files.some(f => f.startsWith(`${phasePrefix}-CONTEXT`));
      const hasResearch = files.some(f => f.startsWith(`${phasePrefix}-RESEARCH`));
      const hasPlan = files.some(f => f.startsWith(`${phasePrefix}-`) && f.includes('-PLAN'));
      const hasSummary = files.some(f => f.startsWith(`${phasePrefix}-`) && f.includes('-SUMMARY'));
      const hasVerification = files.some(f => f.startsWith(`${phasePrefix}-VERIFICATION`));
      const hasPR = files.some(f => f.startsWith(`${phasePrefix}-PR`));
      
      if (hasContext && !hasResearch) {
        console.log(`Next: $gsd-plan-phase ${i}\n`);
        return;
      }
      if (hasPlan && !hasSummary) {
        console.log(`Next: $gsd-execute-phase ${i}\n`);
        return;
      }
      if (hasSummary && !hasVerification) {
        console.log(`Next: $gsd-verify-work ${i}\n`);
        return;
      }
      if (hasVerification && !hasPR) {
        console.log(`Next: $gsd-ship ${i}\n`);
        return;
      }
      if (hasPR) {
        console.log(`Phase ${i} complete. Next: $gsd-discuss-phase ${i + 1}\n`);
        return;
      }
    }
    
    console.log('All phases appear complete!\n');
    console.log('Start new milestone: $gsd-new-milestone "v2.0"\n');
  }

  // Helper methods
  private ensurePlanningDir(): void {
    if (!existsSync(this.planningDir)) {
      mkdirSync(this.planningDir, { recursive: true });
    }
  }

  private isInitialized(): boolean {
    return existsSync(join(this.planningDir, 'PROJECT.md'));
  }

  private detectTechStack(): string[] {
    const techs: string[] = [];
    
    if (existsSync(join(this.cwd, 'package.json'))) {
      techs.push('Node.js/JavaScript');
    }
    if (existsSync(join(this.cwd, 'tsconfig.json'))) {
      techs.push('TypeScript');
    }
    if (existsSync(join(this.cwd, 'Cargo.toml'))) {
      techs.push('Rust');
    }
    if (existsSync(join(this.cwd, 'go.mod'))) {
      techs.push('Go');
    }
    if (existsSync(join(this.cwd, 'requirements.txt')) || existsSync(join(this.cwd, 'pyproject.toml'))) {
      techs.push('Python');
    }
    if (existsSync(join(this.cwd, 'Gemfile'))) {
      techs.push('Ruby');
    }
    
    return techs.length > 0 ? techs : ['Unknown'];
  }

  private analyzeStructure(): string {
    try {
      const entries = readdirSync(this.cwd, { withFileTypes: true });
      return entries
        .filter(e => e.isDirectory() && !e.name.startsWith('.') && !e.name.startsWith('node_modules'))
        .map(e => e.name + '/')
        .slice(0, 10)
        .join('\n');
    } catch {
      return 'Unable to analyze';
    }
  }

  private getPlanFiles(phaseNumber: number): string[] {
    try {
      const files = readdirSync(this.planningDir);
      const prefix = String(phaseNumber).padStart(2, '0');
      return files.filter(f => f.startsWith(prefix) && f.includes('-PLAN'));
    } catch {
      return [];
    }
  }

  private updateState(updates: { currentPhase?: number; status?: string }): void {
    try {
      const statePath = join(this.planningDir, 'STATE.md');
      let content = '';
      
      if (existsSync(statePath)) {
        content = readFileSync(statePath, 'utf-8');
      }
      
      if (updates.currentPhase !== undefined) {
        content = content.replace(/Phase: .*/, `Phase: ${updates.currentPhase}`);
      }
      if (updates.status !== undefined) {
        content = content.replace(/Status: .*/, `Status: ${updates.status}`);
      }
      
      writeFileSync(statePath, content);
    } catch {
      // Ignore
    }
  }
}

// Singleton
let executor: GSDExecutor | null = null;

export function getGSDExecutor(cwd: string): GSDExecutor {
  if (!executor) {
    executor = new GSDExecutor(cwd);
  }
  return executor;
}
